# Junção dos Fields

### IMPORTS

In [1]:
import pandas as pd
import numpy as np
import os

### Datasets dos Fields e Soil

In [2]:
field_dict = {}
for csv in os.listdir(path='./Data_fields/'):
    if csv[:5] == "field":
        if csv[7] == '.':
            field_dict[csv[6]] = pd.read_csv(filepath_or_buffer=f'./Data_fields/{csv}')
        else:
            field_dict[csv[6:8]] = pd.read_csv(filepath_or_buffer=f'./Data_fields/{csv}')
    else:
        soil = pd.read_csv(filepath_or_buffer=f'Data_fields/{csv}')

In [3]:
for i in range(soil.shape[0]):
    field_dict[str(i)] = pd.concat([soil.loc[i].to_frame().transpose(), field_dict[str(i)]], axis=0)

In [6]:
for field in field_dict:
    field_dict[field] = field_dict[field]

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
16,15.0,200.0,9.0,7660.0,1325.0,1304.0,1350.0,1401.0,1480.0,1492.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,334.850
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,272.510
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,489.080
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,474.760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,140.290
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,96.581
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,208.500
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.042
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,264.860

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
17,22.0,200.0,10.0,6102.0,1308.0,1280.0,1359.0,1400.0,1468.0,1479.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,334.850
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,272.510
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,489.080
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,474.760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,140.290
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,96.581
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,208.500
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.042
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,264.860

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
15,16.0,200.0,10.0,7531.0,1314.0,1297.0,1330.0,1391.0,1468.0,1476.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,334.850
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,272.510
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,489.080
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,474.760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,140.290
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,96.581
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,208.500
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.042
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,264.860

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
21,10.0,200.0,8.0,6512.0,1313.0,1287.0,1337.0,1429.0,1488.0,1515.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,332.640
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,279.000
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,494.390
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,465.950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,141.450
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,95.806
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,210.820
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.337
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,273.070

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
27,11.0,200.0,11.0,6172.0,1334.0,1301.0,1357.0,1405.0,1472.0,1494.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,334.850
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,272.510
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,489.080
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,474.760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,140.290
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,96.581
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,208.500
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.042
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,264.860

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
2,2.0,200.0,7.0,7281.0,1266.0,1249.0,1310.0,1387.0,1463.0,1491.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,361.550
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,289.280
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,492.050
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,461.840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,151.720
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,92.301
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,196.660
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,21.461
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,284.040

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
4,7.0,200.0,8.0,6771.0,1305.0,1289.0,1333.0,1438.0,1497.0,1510.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,361.550
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,289.280
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,492.050
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,461.840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,151.720
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,92.301
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,196.660
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,21.461
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,284.040

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
8,25.0,200.0,8.0,6288.0,1327.0,1306.0,1386.0,1434.0,1478.0,1508.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,332.640
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,279.000
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,494.390
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,465.950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,141.450
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,95.806
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,210.820
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.337
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,273.070

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
9,24.0,200.0,11.0,6866.0,1348.0,1308.0,1351.0,1421.0,1481.0,1490.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,332.640
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,279.000
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,494.390
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,465.950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,141.450
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,95.806
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,210.820
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.337
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,273.070

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
13,18.0,200.0,10.0,5836.0,1309.0,1260.0,1353.0,1417.0,1472.0,1489.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,332.640
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,279.000
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,494.390
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,465.950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,141.450
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,95.806
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,210.820
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.337
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,273.070

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
23,8.0,200.0,9.0,7172.0,1346.0,1318.0,1369.0,1421.0,1481.0,1511.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,334.850
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,272.510
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,489.080
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,474.760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,140.290
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,96.581
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,208.500
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.042
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,264.860

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
25,13.0,200.0,7.0,6371.0,1333.0,1301.0,1374.0,1437.0,1502.0,1519.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,334.850
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,272.510
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,489.080
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,474.760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,140.290
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,96.581
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,208.500
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.042
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,264.860

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
11,0.0,200.0,8.0,7885.0,1317.0,1298.0,1365.0,1443.0,1499.0,1522.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,332.640
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,279.000
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,494.390
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,465.950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,141.450
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,95.806
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,210.820
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.337
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,273.070

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
26,12.0,200.0,8.0,6503.0,1326.0,1303.0,1349.0,1411.0,1471.0,1494.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,334.850
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,272.510
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,489.080
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,474.760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,140.290
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,96.581
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,208.500
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.042
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,264.860

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
5,6.0,200.0,11.0,6991.0,1332.0,1324.0,1368.0,1422.0,1484.0,1501.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,361.550
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,289.280
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,492.050
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,461.840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,151.720
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,92.301
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,196.660
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,21.461
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,284.040

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
19,20.0,200.0,7.0,5800.0,1303.0,1265.0,1344.0,1411.0,1477.0,1497.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,332.640
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,279.000
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,494.390
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,465.950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,141.450
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,95.806
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,210.820
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.337
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,273.070

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
1,3.0,200.0,9.0,7272.0,1297.0,1287.0,1323.0,1428.0,1492.0,1508.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,361.550
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,289.280
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,492.050
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,461.840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,151.720
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,92.301
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,196.660
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,21.461
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,284.040

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
18,21.0,200.0,8.0,6186.0,1309.0,1260.0,1345.0,1409.0,1475.0,1498.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,332.640
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,279.000
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,494.390
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,465.950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,141.450
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,95.806
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,210.820
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.337
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,273.070

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
7,26.0,200.0,10.0,6471.0,1327.0,1303.0,1360.0,1424.0,1478.0,1495.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,361.550
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,289.280
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,492.050
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,461.840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,151.720
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,92.301
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,196.660
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,21.461
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,284.040

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
0,4.0,200.0,7.0,6973.0,1345.0,1308.0,1361.0,1413.0,1486.0,1503.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,361.550
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,289.280
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,492.050
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,461.840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,151.720
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,92.301
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,196.660
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,21.461
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,284.040

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
14,17.0,200.0,7.0,6937.0,1327.0,1300.0,1351.0,1431.0,1480.0,1492.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,332.640
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,279.000
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,494.390
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,465.950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,141.450
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,95.806
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,210.820
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.337
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,273.070

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
22,9.0,200.0,8.0,7017.0,1322.0,1300.0,1355.0,1414.0,1475.0,1500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,334.850
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,272.510
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,489.080
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,474.760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,140.290
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,96.581
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,208.500
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.042
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,264.860

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
20,19.0,200.0,9.0,5594.0,1289.0,1255.0,1345.0,1413.0,1468.0,1494.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,332.640
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,279.000
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,494.390
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,465.950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,141.450
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,95.806
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,210.820
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.337
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,273.070

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
10,23.0,200.0,9.0,6959.0,1326.0,1303.0,1360.0,1413.0,1484.0,1495.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,332.640
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,279.000
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,494.390
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,465.950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,141.450
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,95.806
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,210.820
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.337
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,273.070

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
6,5.0,200.0,5.0,7303.0,1322.0,1277.0,1331.0,1416.0,1495.0,1514.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,361.550
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,289.280
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,492.050
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,461.840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,151.720
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,92.301
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,196.660
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,21.461
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,284.040

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
3,1.0,200.0,6.0,7457.0,1297.0,1277.0,1345.0,1409.0,1480.0,1506.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,361.550
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,289.280
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,492.050
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,461.840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,151.720
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,92.301
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,196.660
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,21.461
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,284.040

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
12,27.0,200.0,11.0,6797.0,1332.0,1293.0,1353.0,1416.0,1478.0,1501.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,332.640
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,279.000
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,494.390
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,465.950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,141.450
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,95.806
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,210.820
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.337
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,273.070

,field,BDRICM_BDRICM_M,BDRLOG_BDRLOG_M,BDTICM_BDTICM_M,BLDFIE_sl1,BLDFIE_sl2,BLDFIE_sl3,BLDFIE_sl4,BLDFIE_sl5,BLDFIE_sl6,...,month,year,temperature,dewpoint,windspeed,Soilwater_L1,Soilwater_L2,Soilwater_L3,Soilwater_L4,Precipitation
24,14.0,200.0,9.0,7238.0,1331.0,1297.0,1375.0,1424.0,1496.0,1512.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2002.0,26.008,24.434,1.8453,0.32984,0.32597,0.31477,0.29513,334.850
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2002.0,25.774,24.734,1.9875,0.35884,0.35812,0.35536,0.34368,272.510
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2002.0,25.777,24.609,1.7504,0.35886,0.35896,0.35898,0.36199,489.080
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2002.0,25.890,24.904,1.4950,0.36013,0.35991,0.35997,0.36043,474.760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,2017.0,28.502,23.580,2.0800,0.27522,0.27681,0.28822,0.30790,140.290
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,2017.0,28.604,23.572,2.3288,0.27126,0.26966,0.27516,0.28974,96.581
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,2017.0,28.660,23.361,2.6919,0.25575,0.25560,0.26679,0.27781,208.500
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,2017.0,29.085,22.716,2.5717,0.24774,0.25107,0.26641,0.26837,25.042
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,2017.0,27.948,23.375,2.4586,0.27571,0.27420,0.27366,0.26308,264.860